config/routes.rb
Rails.application.routes.draw do
  resources :users 
  resources :groups do
    resources :posts 
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts do
       resources :comments
  end
  match '/users/confirm_email/:token', to: 'users#confirm_email', via: :get, as: :confirm_email
  match '/groups/accept_invitation/:token', to: 'groups#accept_invitation', via: :get, as: :accept_invitation
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'welcome', to: 'users#welcome', as: 'welcome' 
  get 'add_members/:id', to: 'groups#add_members', as: 'add_members'
  post 'send_invite/:group_id/:user_id', to: "groups#send_invite", as: 'send_invite'
  get 'all_posts', to: 'posts#all_posts', as: 'all_posts'
  get 'reply_comments/:id', to: 'posts#reply_comments', as: 'reply_comments'
  get 'all_reply_comments/:id', to: 'posts#all_reply_comments', as: 'all_reply_comments'
  post 'submit_reply', to: "posts#submit_reply", as: 'submit_reply'
  get 'pending_invitations/:id', to: "groups#pending_invitations", as: 'pending_invitations' 
  post 'invitation_status/:group_id/:id/:process', to: "groups#invitation_status", as: 'invitation_status' 
  post 'post_confirmation/:group_id/:id', to: "posts#post_confirmation", as: 'post_confirmation' 
  delete 'delet_post/:group_id/:id/', :to => 'posts#destroy', as: 'delet_post'

  root :to => "users#welcome"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true, length: { minimum: 5 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = Comment.all
  end

  def show
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
     if !params[:comment][:body].nil? && params[:comment][:body].present?
      @comment = Comment.create(:body=>params[:comment][:body],:user_id=>session[:user_id], :post_id=>params[:post_id])
      flash[:notice] = "Comment was successfully added"
      redirect_to all_posts_path
    else
      flash[:error] = "somthing went wrong"
      redirect_to all_posts_path
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:body, :user_id, :post_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper

	def all_comments(id)
		@comments=Comment.where("post_id=?",id)
	end

	def find_user(comment)
		@user=User.find_by_id(comment.user_id)
	end
	
	def total_replies(comment)
		@all_replies=ReplyComment.where("comment_id=?", comment.id)
	end
	
end

app/views/comments/edit.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/comments/index.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:body) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:post_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to comment.id, comment_path(comment) %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.post_id %></td>
        <td><%=l comment.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      comment_path(comment), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_comment_path(comment), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      comment_path(comment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_comment_path,
            :class => 'btn btn-primary' %>

app/views/comments/new.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/comments/show.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @comment.body %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @comment.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:post_id) %>:</strong></dt>
  <dd><%= @comment.post_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              comments_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_comment_path(@comment), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              comment_path(@comment),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>