config/routes.rb
Rails.application.routes.draw do
  resources :users 
  resources :groups do
    resources :posts 
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts do
       resources :comments
  end
  match '/users/confirm_email/:token', to: 'users#confirm_email', via: :get, as: :confirm_email
  match '/groups/accept_invitation/:token', to: 'groups#accept_invitation', via: :get, as: :accept_invitation
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'welcome', to: 'users#welcome', as: 'welcome' 
  get 'add_members/:id', to: 'groups#add_members', as: 'add_members'
  post 'send_invite/:group_id/:user_id', to: "groups#send_invite", as: 'send_invite'
  get 'all_posts', to: 'posts#all_posts', as: 'all_posts'
  get 'reply_comments/:id', to: 'posts#reply_comments', as: 'reply_comments'
  get 'all_reply_comments/:id', to: 'posts#all_reply_comments', as: 'all_reply_comments'
  post 'submit_reply', to: "posts#submit_reply", as: 'submit_reply'
  get 'pending_invitations/:id', to: "groups#pending_invitations", as: 'pending_invitations' 
  post 'invitation_status/:group_id/:id/:process', to: "groups#invitation_status", as: 'invitation_status' 
  post 'post_confirmation/:group_id/:id', to: "posts#post_confirmation", as: 'post_confirmation' 
  delete 'delet_post/:group_id/:id/', :to => 'posts#destroy', as: 'delet_post'

  root :to => "users#welcome"
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	belongs_to :group
	has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @group = Group.find(params[:group_id])
    @posts = Post.where("group_id=?",params[:group_id])
  end

  def all_posts
    @posts = Post.where("is_approved =?",true)
  end

  def show
  end

  def new
    @group = Group.find(params[:group_id])
    @post = @group.posts.new()
  end

  def edit
    @group = Group.find(params[:group_id])
    @post = Post.find_by_id(params[:id])
  end

  def create
    @group = Group.find(params[:group_id])
    @post = @group.posts.create(post_params)
    @post.user_id = session[:user_id]
    @post.is_approved = (@group.user_id==session[:user_id]) ? true :false
    respond_to do |format|
      if @post.save
        format.html { redirect_to group_posts_path(@group), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @group = Group.find(params[:post][:group_id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to group_posts_path(@group), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group = Group.find(params[:group_id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to group_posts_path(@group), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def reply_comments
    @comment_id=params[:id]
    respond_to do |format|
      format.html
      format.js
    end
  end

  def submit_reply
    @comment_id=params[:id]
    @reply_comments=ReplyComment.create(:body=>params[:body], :comment_id=>params[:comment_id], :user_id=>session[:user_id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def all_reply_comments
    @all_reply_comments=ReplyComment.where("comment_id=?",params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def post_confirmation
    @group=Group.find_by_id(params[:group_id])
    @post=Post.find_by_id(params[:id])
    @post.update_attributes(:is_approved => true)
    flash[:notice] = "post was approved successfully"
    redirect_to group_posts_path(@group)
  end


  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :description)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
	def post_creator(post)
		@group_owner=Group.where("id=? AND user_id=?", post.group_id, session[:user_id])
		@same_user = (post.user_id==session[:user_id])? true : false 
	 	@post_created_user= Group.where("user_id=?", session[:user_id])
		@post_owner= (@group_owner.count>0 || @same_user)? true : false 
	end
end

app/views/posts/_all_reply_comments.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel">All Replies</h4>
</div>
<div class="modal-body">
  <table class="table">
  <%i=0%>
  <%all_replies.each do |reply|%>
      <tr>
        <th scope="row"><%=i=i+1%></th>
        <td>
          <%find_user(reply)%>
          <%=@user.name.capitalize%>
        </td>
        <td>
           <%=reply.body%>
        </td>
        <td>
           <%=reply.created_at.strftime("%e %b %Y %H:%M:%S%p")%>
        </td>
      </tr>
  <%end%>
  </table>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: [ @group, @group.posts.build ], local: true, html:{:class=> "post"}) do |f| %>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>

  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                group_posts_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/posts/_reply_comments.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel">Reply</h4>
</div>
<div class="modal-body">
	<form id="reply_form">
    	<div class="form-group">
		  <textarea class="form-control" rows="3" id="body" name="body"></textarea>
          <input type="hidden" id="comment_id" name="comment_id" value="<%=cmt_id%>">
    </div>
</form>
</div>
<div class="modal-footer">
  <button class="btn btn-primary reply">Save</button>
</div>

<script type="text/javascript">
  $( ".reply" ).click(function() {
  	var postData = $("#reply_form").serialize();
	  $.ajax({
            type: "POST",
            url: "/submit_reply",
            data: postData,
            dataType: "script",
        })
	});
</script>

app/views/posts/all_posts.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1>All posts</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
    </tr>
  </thead>
  <tbody>

    <% @posts.each do |post| %>
       <tr class="post_top">
        <td colspan="2"><h4><%= model_class.human_attribute_name(:title) %>: <%= post.title %></h4>
        </td>
      </tr>
      <tr class="post_top">
        <td ><h4><%= model_class.human_attribute_name(:description) %>:<%= post.description %></h4>
        <td>
      </tr>
      <tr>

          <%@comments=all_comments(post.id)%>
          <td colspan="2">
            <h4>Comments(<%=@comments.count%>)</h4>
            <%@comments.each do |comment|%>
            <%find_user(comment)%>
            <table>
              <tr>
                <td>
                  <%=@user.name.capitalize%>:
                </td>
                <td>
                  <%=comment.body%>
                </td>
                <td>
                  <%=comment.created_at.strftime("%e %b %Y %H:%M:%S%p")%>
                </td>
                <td>
                  <%= link_to 'Reply', reply_comments_path(comment),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary btn-xs'}  %>
               </td>
              </tr>
              <tr>
                <td>
                  
                </td>
                <td>
                  <%total_replies(comment)%>
                  Replies(<%=@all_replies.count%>)
                </td>
                  <td>
                    <% if @all_replies.count > 0%>
                    <%= link_to 'view all', all_reply_comments_path(comment),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary btn-xs'}  %>
                    <%end%>
                  </td>
              </tr>
            </table>
            <%end%>
        </td>
      </tr>
      <tr>
        <td >
        <h5>Add a comment:</h5>
        <%= form_with(model: [ post, post.comments.build ], local: true) do |form| %>
          <p>
            <%= form.text_area :body, :class => "form-control" %>
          </p>
          <p>
            <%= form.submit class: 'btn btn-primary'%>
          </p>
        <% end %>
      </td>
      </tr>
    <% end %>
    <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content"></div>
        </div>
    </div>
  </tbody>
</table>

app/views/posts/all_reply_comments.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'all_reply_comments', all_replies: @all_reply_comments) %>");
$("#modal-window").modal();
$("#modal-window").css("cssText", "display: block !important;");

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%#= form_for @post, :html => { :class => "form-horizontal post" } do |f| %>
<%= form_for @post, as: :post, url: group_post_path(@post), html:{:class=> "post"}, method: :patch do |f| %>



  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
 <%= f.hidden_field :group_id, :value=> @group.id, :class => 'form-control' %>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>


  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                group_posts_path, :class => 'btn btn-default' %>
    </div>
  </div>


<% end %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>

    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <%post_creator(post)%>
        <td>
          <%if @post_owner %>
            <%= link_to t('.show', :default => t("helpers.links.show")),
                        group_post_path(post.group_id, post.id ), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_group_post_path(post.group_id, post.id), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        delet_post_path(post.group_id, post.id),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
             <% if !@group_owner.empty? && post.is_approved!=true%>
             <%= link_to t('.approve', :default => t("helpers.links.approve")),
                          post_confirmation_path(post.group_id, post.id), {:class => 'btn btn-primary btn-xs', :method => :post} %>
            <%end%>           
          <%else%>
                        <p>you don't have any permission of this group</p>
          <%end%>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_group_post_path,
            :class => 'btn btn-primary' %>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header post">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/reply_comments.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'reply_comments', cmt_id: @comment_id) %>");
$("#modal-window").modal();
$("#modal-window").css("cssText", "display: block !important;");

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @post.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @post.description %></dd>
  

</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              group_posts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_group_post_path(@post), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              group_posts_path(@post),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/posts/submit_reply.js.erb
// $("#modal-window").css("cssText", "display: none !important;");
// $("#modal-window").display("none");
document.location.reload()