config/routes.rb
Rails.application.routes.draw do
  resources :users 
  resources :groups do
    resources :posts 
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts do
       resources :comments
  end
  match '/users/confirm_email/:token', to: 'users#confirm_email', via: :get, as: :confirm_email
  match '/groups/accept_invitation/:token', to: 'groups#accept_invitation', via: :get, as: :accept_invitation
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'welcome', to: 'users#welcome', as: 'welcome' 
  get 'add_members/:id', to: 'groups#add_members', as: 'add_members'
  post 'send_invite/:group_id/:user_id', to: "groups#send_invite", as: 'send_invite'
  get 'all_posts', to: 'posts#all_posts', as: 'all_posts'
  get 'reply_comments/:id', to: 'posts#reply_comments', as: 'reply_comments'
  get 'all_reply_comments/:id', to: 'posts#all_reply_comments', as: 'all_reply_comments'
  post 'submit_reply', to: "posts#submit_reply", as: 'submit_reply'
  get 'pending_invitations/:id', to: "groups#pending_invitations", as: 'pending_invitations' 
  post 'invitation_status/:group_id/:id/:process', to: "groups#invitation_status", as: 'invitation_status' 
  post 'post_confirmation/:group_id/:id', to: "posts#post_confirmation", as: 'post_confirmation' 
  delete 'delet_post/:group_id/:id/', :to => 'posts#destroy', as: 'delet_post'

  root :to => "users#welcome"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Testmeet" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Testmeet</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <%if session[:user_id]%>
            <li><%= link_to "Group", "/groups"  %></li>
            <li><%= link_to "Post", "/all_posts"  %></li>
            <li><%= link_to "Pending group Requests", "/pending_invitations/#{session[:user_id]}"  %></li>
            <%end%>
          </ul>
          <ul style="float:right;margin-top: 1.5%;">
              <% if current_user %>
                Welcome <%= current_user.name.capitalize %>!!
              <%= link_to "Log Out", logout_path %>
              <% else %>
                <%= link_to "Sign Up", "/users/new" %> or 
                <%= link_to "Log In", login_path %>
              <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <!-- <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div> --><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2019</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>